# Docker
# Build and push an image to Azure Container Registry
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

variables:
  containerRegistry: 'azurecicdtestkimoji.azurecr.io'
  imageName: 'azure-cicd-test'
  tag: '$(Build.BuildId)'

steps:
  - task: NodeTool@0
    inputs:
      versionSpec: '20.x'
    displayName: 'Install Node.js'

  - script: |
      npm install
      npm run build
    displayName: 'Install dependencies and build Vue app'

  - task: Docker@2
    inputs:
      containerRegistry: '$(containerRegistry)'
      repository: '$(imageName)'
      command: 'buildAndPush'
      Dockerfile: '**/Dockerfile'
      tags: |
        $(tag)
