# Docker
# Build and push an image to Azure Container Registry
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- main

variables:
  - name: API_URL
    value: 'http://192.168.50.91:8088'

steps:
- task: Docker@2
  inputs:
    containerRegistry: 'azurecicdtestkimoji'
    repository: 'azure-cicd-test'
    command: 'buildAndPush'
    Dockerfile: '**/Dockerfile'
    buildContext: '$(System.DefaultWorkingDirectory)'
    tags: |
      $(Build.BuildId)
      latest
  env:
    API_URL: $(API_URL)

- task: AzureContainerApps@1
  inputs:
    azureSubscription: 'azure-cicd-test-subscription'
    containerAppName: 'azure-cicd-test'
    resourceGroup: 'azure-cicd-test'
    imageToDeploy: 'azurecicdtestkimoji.azurecr.io/azure-cicd-test:$(Build.BuildId)'
